---
title       : "R Fundamentals"
author      : "William R. Buchanan, Ph.D." 
job         : "Strategic Data Fellow at MDE/Adjunct Prof at JSU"
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides

---
`r opts_chunk$set(message = FALSE)`

## Overview 
* Review
* Break from the norm
* Next Class

---

## Review
* Generally much better than the first assignment.  
* Try to focus more effort on conclusions that you could draw from the graphs/results and less effort on describing the descriptive 
* Changing the axis titles/labels does not change the graph; several people lost points because they graphed the same data twice for the same question (and in some cases provided the same answer)

---   

## Break from the norm
* Since several people still seem to be struggling with using R in general, I decided to break away from the syllabus and take a bit of time to develop some R skills.  
	+ This is also a way of introducing you to the tool that you'll be using for the next class meeting
	+ Like R and R Studio, it is a free tool, but it is completely web based
	+ It should also help you to get used to working with other datasets and data structures
* So, everyone should now open their web browsers and go to [www.DataCamp.com](http://www.datacamp.com) 	
* Once there, you can register using any method you'd like, but it would probably be best/easiest to use your JSU email account for your email address (they won't blast your inbox with spam, so you won't need to worry about that)

---   

## Next Class
* School and District accountability results should be released to the public this Friday; look at the results and think about what they mean from a policy/practical position.
	+ If no schools were 100% proficient, all schools would be facing some rough waters under NCLB
	+ Would you rather face the consequences outlined under NCLB or get the flexibility waiver and work on aligning your curricula to the new standards?  
	+ If you go to MDE's reporting site, download the data file and create some graphs; Is there anything that looks good/bad/unexpected?
* I have to go to a conference down on the Coast next week, but will provide links for material to watch online as well as some additional work using [DataCamp](http://www.datacamp.com)  



















